# Generated by Django 5.2.12 on 2026-03-15 23:06

from django.db import migrations


def verify_existing_customers(apps, schema_editor):
    """Mark all pre-existing customers as verified (they registered before email verification was added)."""
    Customer = apps.get_model('market', 'Customer')
    Customer.objects.filter(is_verified=False).update(is_verified=True)


def reverse_verify(apps, schema_editor):
    pass  # No meaningful reverse


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_seed_categories'),
    ]

    operations = [
        migrations.RunPython(verify_existing_customers, reverse_verify),
    ]
