# Generated by Django 5.2.12 on 2026-03-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_add_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password_reset_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
