# Generated by Django 5.2.12 on 2026-03-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product_description_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(db_index=True, max_length=200)),
                ('sender', models.CharField(max_length=100)),
                ('role', models.CharField(default='customer', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
