# Generated by Django 5.2.12 on 2026-03-15 22:37

from django.db import migrations


CATEGORIES = [
    'General', 'Dairy', 'Bakery', 'Beverages', 'Snacks',
    'Fruits', 'Vegetables', 'Frozen', 'Stationery', 'Other',
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model('market', 'Category')
    for name in CATEGORIES:
        Category.objects.get_or_create(name=name)


def unseed_categories(apps, schema_editor):
    Category = apps.get_model('market', 'Category')
    Category.objects.filter(name__in=CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_category_notification_customer_is_verified_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
