# Generated by Django 5.2.12 on 2026-03-16 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_chatmessage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_name_snapshot',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.product'),
        ),
    ]
