from django.urls import path
from . import api_views

urlpatterns = [
    path('customer/register/', api_views.customer_register, name='api_customer_register'),
    path('customer/login/', api_views.customer_login, name='api_customer_login'),
    path('staff/register/', api_views.staff_register, name='api_staff_register'),
    path('staff/login/', api_views.staff_login, name='api_staff_login'),
    path('logout/', api_views.logout, name='api_logout'),
    path('verify/', api_views.verify_email_api, name='api_verify_email'),
    path('forgot-password/', api_views.forgot_password, name='api_forgot_password'),
    path('reset-password/', api_views.reset_password, name='api_reset_password'),
    path('customer/profile/', api_views.customer_profile, name='api_customer_profile'),
    path('products/', api_views.product_list, name='api_products'),
    path('products/publish/', api_views.publish_product, name='api_publish_product'),
    path('products/my/', api_views.my_products, name='api_my_products'),
    path('products/seller-stats/', api_views.seller_stats, name='api_seller_stats'),
    path('products/<int:product_id>/', api_views.update_product, name='api_update_product'),
    path('products/<int:product_id>/delete/', api_views.delete_product, name='api_delete_product'),
    path('categories/', api_views.category_list, name='api_categories'),
    path('orders/', api_views.place_order, name='api_place_order'),
    path('orders/my/', api_views.my_orders, name='api_my_orders'),
    path('orders/<int:order_id>/confirm/', api_views.confirm_receipt, name='api_confirm_receipt'),
    path('staff/orders/', api_views.staff_orders, name='api_staff_orders'),
    path('staff/orders/<int:order_id>/', api_views.update_order_status, name='api_update_order'),
    path('staff/inventory/', api_views.inventory, name='api_inventory'),
    path('staff/inventory/<int:product_id>/', api_views.update_inventory, name='api_update_inventory'),
    path('staff/inventory/<int:product_id>/toggle-active/', api_views.toggle_product_active, name='api_toggle_product_active'),
    path('favorites/', api_views.favorite_list, name='api_favorites'),
    path('favorites/toggle/', api_views.favorite_toggle, name='api_favorite_toggle'),
    path('refunds/', api_views.create_refund, name='api_create_refund'),
    path('refunds/my/', api_views.my_refunds, name='api_my_refunds'),
    path('staff/refunds/', api_views.staff_refund_list, name='api_staff_refunds'),
    path('staff/refunds/<int:refund_id>/', api_views.process_refund, name='api_process_refund'),
    path('notifications/', api_views.notification_list, name='api_notifications'),
    path('notifications/count/', api_views.notification_count, name='api_notification_count'),
    path('notifications/<int:notif_id>/read/', api_views.notification_mark_read, name='api_notification_read'),
    path('notifications/<int:notif_id>/delete/', api_views.notification_delete, name='api_notification_delete'),
    path('chat/rooms/', api_views.chat_rooms, name='api_chat_rooms'),
    path('chat/rooms/<str:room_name>/delete/', api_views.delete_chat_room, name='api_delete_chat_room'),
]
