# Generated by Django 5.2.12 on 2026-03-16 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_verify_existing_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.product'),
        ),
    ]
