# Generated by Django 5.2.12 on 2026-03-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_orderitem_product_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
